language: node_js
node_js:
  - "node"
env:
  - SCRIPT=lint
  - SCRIPT=type-check
  - SCRIPT=build
script:
  - yarn run $SCRIPT
stages:
  - name: test
  - name: release
    if: tag =~ ^v\d
jobs:
  include:
    - stage: release
      node_js: "node"
      env: SCRIPT=build
      script: yarn run $SCRIPT
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_AUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
          branch: master
cache:
  yarn: true
notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#hearthsim-commits"
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
